apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d6e5h99o5-go
  janus-idp.io/tekton: d6e5h99o5-go
  backstage.io/kubernetes-id: d6e5h99o5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d6e5h99o5-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
